//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BGOUGEntities : DbContext
    {
        public BGOUGEntities()
            : base("name=BGOUGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<interest> interests { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<members_events> members_events { get; set; }
        public virtual DbSet<platform> platforms { get; set; }
    }
}
