//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string position { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public short typeMemebrship { get; set; }
        public bool isPaidMembership { get; set; }
        public short discountAllowance { get; set; }
        public int currentCompany { get; set; }
        public Nullable<int> interestFK { get; set; }
        public Nullable<int> platformFK { get; set; }
        public Nullable<int> referencedBy { get; set; }
    
        public virtual company company { get; set; }
        public virtual interest interest { get; set; }
        public virtual members_events members_events { get; set; }
        public virtual platform platform { get; set; }
    }
}
