//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class members_events
    {
        public int IDMembers { get; set; }
        public Nullable<int> IDEvents { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual member member { get; set; }
    }
}
